README.md, docs/README.md, website/templates/index.jsx
=> Documentation Grammer Edit

examples/camera/package.json, examples/terrain/package.json, examples/trips/package.json, modules/core/package.json, package.json, website/package.json, yarn.lock
Fixes a mismatched version of luma.gl error.
=> Upgrade luma.gl to 8.3.1

modules/core/src/adapters/deck-adapter.js, modules/react/src/components/export-video/export-video-panel-container.js
Add optional to DeckAdapter glContext for test-utils.
=> Add optional to DeckAdapter glContext for test-utils.

modules/react/src/components/export-video/export-video-panel-preview.js
Removes hardcoding. Tested kepler-integration and worldview examples.
=> Use the active map style

docs/README.md, examples/camera/app.js, examples/terrain/app.js, examples/worldview/src/features/renderer/rendererMiddleware.js, examples/worldview/src/features/stage/StageMap.js, modules/core/docs/deck-adapter.md, modules/core/docs/encoder/preview-encoder.md, modules/core/src/adapters/deck-adapter.js, modules/core/src/scene/deck-scene.js, modules/react/src/components/basic-controls.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/quick-animation.js
- adapter.getProps & adapter.render changed to object params
- rename scene.getLayers to scene.getScene
=> Use object parameters for functions

examples/worldview/src/features/stage/StageMap.js
- layer visibility
- layer order
=> Align layer rendering with kepler.gl

examples/worldview/src/features/stage/Stage.js, examples/worldview/src/features/stage/StageContainer.js, examples/worldview/src/features/stage/StageMap.js, modules/core/src/adapters/deck-adapter.js, modules/core/src/scene/deck-scene.js
- prepareFrame is a function called following a frame render that preforms next-frame preparation (assumes time step has increment).
=> Renaming getFilters to prepareFrame

examples/worldview/src/app/App.js, examples/worldview/src/features/kepler/hooks.js, examples/worldview/src/features/renderer/index.js, examples/worldview/src/features/stage/Stage.js, examples/worldview/src/features/stage/StageContainer.js, examples/worldview/src/features/stage/StageMap.js, examples/worldview/src/features/timeline/hooks.js
- Remove kepler state selectors from within Stage component.
- Create hooks for kepler keyframes and frame preparation.
- Add deckProps and staticMapProps override
- TODO: Remove kepler state selectors StageMap and StageContainer too.
- TODO: timeline reducer contains kepler-specific keyframe state. Looking to be more flexible.
=> Add more hooks and improve isolation of kepler.gl within components

examples/worldview/src/app/App.js, examples/worldview/src/features/kepler/hooks.js, examples/worldview/src/features/stage/StageMap.js, examples/worldview/src/scenes/newYork/index.js, modules/core/docs/deck-adapter.md, modules/core/src/adapters/deck-adapter.js
- Allow external libraries to add deck props in rendering component, such as layers or parameters.
- Docs
=> Adding extraProps to DeckAdapter

examples/worldview/src/features/monitor/MonitorPanel.js, examples/worldview/src/features/renderer/rendererSlice.js
UI component is a standard slider for now:
Builds on #98
=> [feat] add SeekSlider UI component to preview animation

examples/kepler-integration/src/components/export-video.js, examples/worldview/package.json, examples/worldview/src/features/map/Map.js, modules/react/package.json, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/export-video/export-video-panel.js, modules/react/src/components/export-video/utils.js
Add <ExportVideoPanelContainer/> props to override deck and static map components.
=> [chore] pass deckProps and staticMapProps to ExportVideoPanelContainer

examples/worldview/src/features/map/Map.js
=> [bug] typo in worldview video resize

examples/worldview/src/features/map/Map.js, examples/worldview/src/features/map/MapContainer.js, examples/worldview/src/features/monitor/MonitorPanel.js, examples/worldview/src/features/renderer/rendererMiddleware.js, examples/worldview/src/features/timeline/timelineSlice.js
- fixes render %
- UI slider is now controlled by store
=> [enhancement] worldview add timecursor UI for playback seeking

examples/kepler-integration/src/components/export-video.js, examples/kepler-integration/src/reducers/index.js, modules/react/src/components/export-video/export-video-panel-container.js
Apply these props to `ExportVideoPanelContainer`
```
import {setFilter, setLayerAnimationTime, updateMap} from 'kepler.gl/actions';
const mapDispatchToProps = {
onFilterFrameUpdate: setFilter,
onTripFrameUpdate: setLayerAnimationTime,
onCameraFrameUpdate: updateMap
}
```
=> [enhancement] add kepler animations to integration example

modules/core/src/keyframes/kepler-filter-keyframes.js, modules/core/test/index.js, modules/core/test/keyframes/kepler-filter-keyframes.spec.js
Signed-off-by: Shan He <heshan0131@gmail.com>
=> support kepler.gl filter animate by interval keyframes

modules/react/src/components/export-video/utils.js
- Improved old GIF file size estimation formula
- Added estimations for all supported formats
=> File Size Estimation Improvements

examples/kepler-integration/README.md
- Updated instructions on accessing modal
- Added screenshots and updated link on live deployment
- Documented the ability to animate time ranges
- Added section on basic usage
=> Documentation Updates

examples/quick-start/webpack.config.js, examples/webpack.config.local.js, modules/core/src/adapters/deck-adapter.js
**Tested & Working**
camera
quick-start
terrain
trips
kepler-integration
worldview (new york cluster and sf trees bars)
=> fix(examples) check for deck before reference

examples/worldview/src/features/monitor/MonitorPanel.js
To be used when demoing requirements in #159.
https://user-images.githubusercontent.com/2461547/136089795-670fab90-3b20-4976-8f89-eedf07ac3def.mov
=> add(worldview) dimension picker demo

modules/react/src/components/export-video/export-video-panel-container.js
- add animatableFilter prop for export-video-panel-container to manually specify animatable filters
=> fix(animation): add animatableFilters prop for export-video-panel-container

modules/react/src/components/export-video/export-video-panel-preview.js
- map.remove causes issues when the video export modal is closed for the second time
=> fix(kepler-integration): remove mapboxMap.remove

modules/core/src/animations/kepler-animation.js, modules/core/src/keyframes/kepler-filter-keyframes.js, modules/react/src/components/export-video/export-video-panel-container.js
- add getTimeRangeFilterKeyframes prop for export-video-panel-container to provide custom filter keyframes generation logic
=> fix(animation): add getTimeRangeFilterKeyframes prop for export-video-panel-container

yarn.lock
=> chore(deps) update browser list

docs/README.md, examples/basic-basemap/app.js, examples/camera/app.js, examples/camera/layers.js, examples/pure-js/app.js, examples/quick-start/app.js, examples/terrain/app.js, examples/trips/app.js, examples/worldview/src/scenes/newYork/index.js, examples/worldview/src/scenes/sftrees/index.js, modules/core/package.json, modules/core/src/keyframes/utils.js, modules/core/test/keyframes/camera-keyframes.spec.js, modules/core/test/keyframes/utils.spec.js, modules/react/package.json, modules/react/src/components/export-video/export-video-panel-container.js, scripts/bundle.config.js, test/browser.js, webpack.config.js, yarn.lock
- update popmotion and imports
- updated webpack to support `.mjs` (used by newer popmotion) due to https://stackoverflow.com/a/69343125
=> update(deps) update to popmotion v11

modules/react/src/components/export-video/modal-tab-animation.js, modules/react/src/components/export-video/utils.js, modules/react/test/components/export-video.spec.js, modules/react/test/index.js, test/modules.js
=> refactor(react) add hours and milli options to duration printer

examples/website/basic-basemap-mapbox-legacy/app.jsx, examples/website/basic-basemap-mapbox/app.jsx, examples/website/basic-basemap/README.md, examples/website/basic-basemap/app.jsx, examples/website/camera/app.jsx, examples/website/terrain/app.jsx, examples/website/trips/README.md, examples/website/trips/app.tsx, examples/website/trips/package.json, modules/core/src/animations/deck-animation.ts, modules/react/src/components/basic-controls.tsx, modules/react/src/hooks.ts
Trying to remove the need for api keys
=> Use maplibre in trips example

examples/kepler/vite.config.js, modules/core/src/animations/kepler-animation.ts, modules/react/package.json, modules/react/src/components/export-video/export-video-panel-container.tsx, modules/react/src/components/export-video/export-video-panel-preview.tsx, modules/react/src/kepler-layers.ts, website/yarn.lock, yarn.lock
For #266
- [fix(react) kepler layers should be visible](https://github.com/visgl/hubble.gl/commit/ca5e3ea5015d829fcf0e0ced6a123916730998e5)
- [fix(kepler) layers should update on every react render](https://github.com/visgl/hubble.gl/commit/88bdf6c9f234b68c1c661fd3dc2aad9462cca40d)
- [chore(kepler) component should configure which map to render](https://github.com/visgl/hubble.gl/commit/2d07fafe3b9822ccb186b31d8acb15972749b8d9)
- [change(kepler) switch png and jpeg encoder to use zip archives](https://github.com/visgl/hubble.gl/commit/fa7680f18ecaa84d74e4f4c0396870816fd44338)
- [fix(kepler) filters should render enlarged filters using latest schema](https://github.com/visgl/hubble.gl/commit/47d469141a0caf3589b5e5430cce7f0c7f90edff)
- [fix(kepler) all defined filters should …
=> fix(kepler) 3.1 integration

examples/get-started/pure-js/package.json, examples/get-started/scripting/index.html, examples/kepler/package.json, examples/website/basic-basemap-mapbox-legacy/package.json, examples/website/basic-basemap-mapbox/package.json, examples/website/basic-basemap/package.json, examples/website/camera/package.json, examples/website/quick-start/package.json, examples/website/terrain/package.json, examples/website/trips/package.json, lerna.json, modules/core/package.json, modules/main/package.json, modules/react/package.json, website/package.json, yarn.lock
- use hubble 1.4
- remove unused deps
=> chore: use 1.4 and remove unused deps

docs/api-reference/animations/deck-animation.md, docs/api-reference/keyframe/deck-layer-keyframes.md, docs/api-reference/keyframe/keyframes.md, examples/website/camera/layers.js, examples/website/terrain/app.jsx, modules/core/src/animations/animation.ts, modules/core/src/animations/deck-animation.ts, modules/core/src/animations/kepler-animation.ts, modules/core/src/keyframes/camera-keyframes.ts, modules/core/src/keyframes/deck-layer-keyframes.ts, modules/core/src/keyframes/kepler-filter-keyframes.ts, modules/core/src/keyframes/kepler-layer-keyframes.ts, modules/core/src/keyframes/kepler-trip-keyframes.ts, modules/core/src/keyframes/keyframes.ts, modules/core/src/keyframes/utils.ts, modules/core/test/keyframes/camera-keyframes.spec.ts
=> Remove `activeFeatures` from Keyframes and `animator` apis from Animation

examples/get-started/pure-js/package.json, examples/get-started/scripting/index.html, examples/kepler/package.json, examples/website/basic-basemap-mapbox-legacy/package.json, examples/website/basic-basemap-mapbox/package.json, examples/website/basic-basemap/package.json, examples/website/camera/package.json, examples/website/quick-start/package.json, examples/website/terrain/package.json, examples/website/trips/package.json, modules/react/package.json, website/yarn.lock, yarn.lock
Resolves part of #321
Please review and advise @chrisgervang 
Thank you
=> chore(deps): bump modules and examples to 2.0.0-alpha.3
