modules/core/src/encoders/encoder.js, modules/core/src/encoders/tar/tar-encoder.js, modules/core/src/encoders/utils/preview-encoder.js, modules/core/src/encoders/video/stream-encoder.js, modules/core/src/encoders/video/webm-encoder.js
These functions are not used anymore, so the interface can be simplified.
=> Remove stop and dispose from FrameEncoders

modules/core/src/encoders/tar/tar-encoder.js, modules/core/src/encoders/utils/index.js
In rare situations when a canvas is captured before an animation frame is finished, toDataUrl can return a nearly empty string. It is useful to warn when this happens, but it is no longer considered an error since proper usage of the library guarantees the canvas is captured appropriately. 
The only time we expect this nearly empty string is when capturing a truly empty frame, such as a transparent PNG when deckgl doesn't have anything to render. 
A regression could reintroduce this issue, especially when @deck.gl/mapbox support is added (fusing canvases is a fragile operation).
See a before and after example on [gdrive](https://drive.google.com/drive/folders/1-e9yY4W33moZF_ewCTUPOeFsGcHh66Ex?usp=sharing)
=> Renable PNGEncoder blank (transparent) frames

docs/README.md, docs/whats-new.md, examples/minimal/app.js, examples/minimal/scene.js, examples/terrain/app.js, examples/terrain/scene.js, modules/core/docs/deck-adapter.md, modules/core/docs/encoder/README.md, modules/core/docs/encoder/jpeg-sequence-encoder.md, modules/core/docs/encoder/webm-encoder.md, modules/core/src/adapters/deck-adapter.js, modules/core/src/capture/video-capture.js, modules/core/src/scene/deck-scene.js, modules/core/src/scene/kepler-scene.js, modules/core/src/types.d.ts, package.json
- scene settings are defined at scene load time, so you can set scene resolution and animation length there.
```ts
interface DeckSceneParams {
lengthMs: number
width: number
height: number
animationLoop: any
keyframes: any
data: any
renderLayers: (scene: DeckScene) => any[]
}
```
- encoder settings are defined before every render, so you  can set seek options there.
```ts
interface EncoderSettings {
startOffsetMs?: number
durationMs?: number  
filename: string
framerate: number
jpeg: {
quality: number
},
webm: {
quality: number
}
}
```
=> Refactor encoder settings and scene settings api

examples/camera/app.js, examples/camera/scene.js, examples/terrain/app.js, examples/terrain/scene.js, modules/react/src/components/index.js, modules/react/src/components/resolution-guide.js
Adding this to examples so the background doesn't look so empty, and shipping in `@hubble.gl/react` for reuse.
=> Adding a ResolutionGuide component.

modules/core/src/adapters/deck-adapter.js, package.json, yarn.lock
Following up on https://github.com/visgl/deck.gl/pull/4574, hubble.gl does not need to instantiate and attach its own Timeline object anymore. In fact, it would introduce buggy behavior since deck.gl maintains two references to the timeline object and hubble.gl can only update one.
=> Assume timeline is always defined in DeckAdapter

dev-docs/v1.2/using-kepler-components-rfc.md, dev-docs/vNext/using-kepler-components-rfc.md
RFC: Integration - Using Kepler.gl Components in External Libraries
The area this RFC discusses is specifically how an external library like, hubble.gl, can reuse React components written in kepler.gl. We'll explore four options and their pros/cons.
We've implemented Option D [here](https://github.com/uber/hubble.gl/commit/7e41dd4fdef16a0602425dc40d15fd8e567beb51)
=> Proposal: Using Kepler.gl Components in External Libraries

modules/react/src/components/export-video/constants.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-settings.js, modules/react/src/components/export-video/export-video-panel.js
**Summary**
- Simplify ExportVideoPanelContainer derived state
- Derive encoderSettings and canvasWidth/Height during render
- Use `<ItemSelector>` with const options and accessors
- Rename `quality` to `resolution`
The logic in ExportVideoPanelContainer gets hairy because its `this.state` includes both source-of-truth data (like `quality`) and derived data (like `canvasWidth` and `encoderSettings`).
A more react-like solution is to only store the source data in the state, and derive `encoderSettings` and `canvasWidth` on the fly during rendering. This can cause some redundant computation but ensures derived state is always up to date.
The format of `qualitySettings` being the human-readable label will break if localized to another language. A better way is to use `<ItemSelector>` as …
=> Simplify derived react state + cleanup

examples/kepler-integration/src/components/export-video.js, modules/react/src/components/export-video/constants.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-footer.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/export-video/export-video-panel-settings.js, modules/react/src/components/export-video/export-video-panel.js, modules/react/src/components/index.js, modules/react/src/components/inject-kepler.js, package.json, yarn.lock
- Inject kepler.gl/components via KeplerUI react context
- Add plugin-transform-runtime to add regeneratorRuntime into the build if it's missing (helps with kepler.gl integration)
- Store resolution as WxH to make options forward compatible
- Make modal title bar optional
- Resolve deck/luma dependencies to 8.2 to match kepler
- Allow export modal state to be persisted outside and rehydrated
=> Kepler.GL integration tweaks

examples/camera/package.json, examples/kepler-integration/package.json, examples/kepler-integration/src/app.js, examples/trips/package.json, modules/core/package.json, modules/react/src/components/export-video/constants.js, modules/react/src/components/export-video/export-video-modal.js, modules/react/src/components/export-video/export-video-panel-settings.js, modules/react/src/components/export-video/export-video-panel.js, package.json, yarn.lock
- Remove kepler.gl/ includes from react components entirely
- Replace `DIMENSIONS` from `kepler.gl/constants` with the single constant we use. This is fixed in kepler.gl anyway.
- Move ReactIntl integration to `kepler-integration` example to remove `kepler.gl/localization` dependency from component. This context is already provided inside kepler.gl.
- Move luma.gl to a peer dependency of the sub-packages to avoid version conflicts with examples
- Move `react-intl` dep to top level to avoid duplicated intl context instances in example
- Pin more luma/deck versions to 8.2.0 to match kepler
=> Remove kepler.gl recursive includes

examples/kepler-integration/src/components/export-video.js, modules/core/src/capture/video-capture.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-footer.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/export-video/export-video-panel-settings.js, modules/react/src/components/export-video/export-video-panel.js, modules/react/src/components/export-video/utils.js
- Pressing "Render" now gives user feedback by showing Kepler's spinner. Note that this does not happen when "Preview" is pressed. Options are disabled while rendering.
- DeckGL layers no longer clips
- Time conversion now only shows 1 digit
- Size of duration now equal with the other sections
- Black 50% opacity overlay
- Spinner & total time match up. Save function in video-capture.js made asynchronous
- Percentage now below spinner showing % done
- Styling does not match Kepler. Or % won't be visible on all backgrounds
=> Rendering feedback - Spinner

modules/core/docs/deck-adapter.md
Callbacks were changed in #58 to happen right after saving.
https://github.com/uber/hubble.gl/pull/58/files#diff-f2b2ddef3003d116a87f5e29beee8a5ab978e06627958732dd8972fa9d3d9d0dR164
=> Updated onStop documentation

modules/core/src/encoders/video/gif-encoder.js, modules/core/src/types.d.ts
Changing JPEG quality from 80% to 100% for GIF input frames decreases GIF size in testing and increases quality. Leave the compression to the GIF library.
Resolution | 80% | 100%
------------ | ------------ | -------------
720p | 15.8MB | 13.7MB
1080p | 34.6MB | 21.2MB
=> Add jpegQuality to GIF and default to 1.0

examples/worldview/src/features/kepler/keplerSlice.js, examples/worldview/src/features/stage/Stage.js
- Synchronizes kepler's mapState with hubble's whenever it is updated so that zoom-based scaling correctly applies to layers.
Supports keyframe definitions on scene now using special object keys.
Supported Keyframes (by key name):
- `camera`: mapState animation
- `hubble_timeFilter` applies time filter keyframe to first time filter listed in kepler. (only one filter is supported right now)
- any `visConfig` of a layer can by animated by using the layer's `label` as a key.
**This interface is very experimental, and will change.**
=> Support animations of visConfig, filters, and mapState

examples/worldview/src/features/renderer/hooks.js, examples/worldview/src/features/stage/Stage.js
Removes logic from render function, and adds reusable hooks.
=> Adding usePreviewHandler and useRenderHandler hook

examples/worldview/src/app/App.js, examples/worldview/src/features/kepler/hooks.js, examples/worldview/src/features/kepler/index.js, examples/worldview/src/features/kepler/keplerSlice.js, examples/worldview/src/features/stage/StageContainer.js, examples/worldview/src/features/stage/StageMap.js
- useKeplerDeckLayers hook to create deck layers from kepler redux store.
- selectMapStyle selector to inject map style from kepler redux store.
- kepler selectors support any "store map id" with createSelectKeplerLayers, createSelectKeplerMap, createSelectMapStyle.
- TODO: match kepler.gl layer creation better.
=> Kepler now external to worldview components

examples/worldview/src/features/stage/Stage.js, examples/worldview/src/features/stage/StageMap.js, examples/worldview/src/features/stage/utils.js
Video dimensions cannot be odd in many video formats. Solution: Round scaling factors to the closest even factor to always get an even resolution in the final video. [Any number multiplied by 2 is even.](https://www.theguardian.com/notesandqueries/query/0,5753,-2212,00.html#:~:text=EVEN%20NUMBERS%20can%20be%20looked,can%20be%20described%20as%202n.&text=Therefore%2C%20any%20even%20number%20plus,some%20number%20multiplied%20by%20two)
The ratio is a scaling factor and uses float (e.g. 1.345), whereas the dimensions represent pixels and those should be int (e.g. 1080 or 720).
=> [bug fix] odd dimensions cause encoder issues

examples/worldview/src/features/kepler/hooks.js, examples/worldview/src/features/timeline/timelineSlice.js
When a kepler json with an active trip layer is loaded, the `setLayerAnimationTime` can be animated with keyframes stored in redux using the following action. Applying the animation happens automatically within the worldview kepler hook.
Usage in user code:
```
dispatch(updateTripLayerKeyframes({
timings: [0, 1000, 2000],
keyframes: [
{time: 1671000000000},
{time: 1671001000000},
{time: 1671002000000}
],
easings: easing.linear
}));
```
=> [feat] add tripLayerKeyframe for Kepler Trip Layer support

docs/README.md, modules/core/docs/deck-adapter.md, modules/core/docs/encoder/frame-encoder.md, modules/core/docs/scene/deck-scene.md, modules/core/src/adapters/deck-adapter.js, modules/core/src/capture/video-capture.js, modules/core/src/scene/deck-scene.js, modules/core/src/types.d.ts
```
timecode = {
start?: number, // default 0
end: number,
framerate?: number // default 30
duration?: number // end - start
}
```
- Timecode can be used to for partial previews and renders by specifying any start or end time in the animation.
- Previously the duration parameter assumed every render and preview started at time zero.
- framerate has been moved from encoderSettings to timecode.
- filename has been moved out of encoderSettings as well.
- lengthMs has been removed from DeskScene. Just supply timecode instead.
=> [refactor] Remove duration, use timecode instead

examples/camera/app.js, examples/quick-start/app.js, examples/quick-start/quick-start-after.js, examples/terrain/app.js, examples/trips/app.js, examples/worldview/src/features/renderer/rendererMiddleware.js, examples/worldview/src/features/renderer/rendererSlice.js, modules/react/src/components/basic-controls.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/quick-animation.js
=> [refactor] Add timecode to examples

examples/camera/app.js, examples/terrain/app.js, examples/trips/app.js, examples/worldview/src/features/renderer/rendererMiddleware.js, modules/core/docs/deck-adapter.md, modules/core/src/adapters/deck-adapter.js, modules/core/src/capture/video-capture.js, modules/core/src/types.d.ts, modules/react/src/components/basic-controls.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/quick-animation.js
Formats can be configured with the following passed into `DeckAdapter.render({formatConfigs})`
```
interface FormatConfigs {
jpeg: {
quality: number
},
webm: {
quality: number
}
gif: {
numWorkers: number,
sampleInterval: number,
width: number,
height: number
jpegQuality: number
}
}
```
=> [chore] rename encoderSettings to formatConfigs

docs/README.md, examples/camera/app.js, examples/terrain/app.js, examples/trips/app.js, examples/worldview/src/features/map/MapContainer.js, modules/core/docs/deck-adapter.md, modules/core/docs/keyframe/camera-keyframes.md, modules/core/docs/scene/deck-scene.md, modules/core/src/adapters/deck-adapter.js, modules/core/src/scene/deck-scene.js, modules/core/src/scene/kepler-scene.js, modules/core/src/types.d.ts, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/quick-animation.js
Hubble only uses features of the Timeline object. Eventually it would be great if Hubble could supply a timeline to deck instead of the other way around, since we can then remove the `sceneBuilder` callback.
=> [chore] use Timeline instead of AnimationLoop

docs/README.md, modules/core/docs/deck-adapter.md, modules/core/docs/scene/deck-scene.md, modules/core/src/scene/deck-scene.js, modules/core/src/scene/kepler-scene.js, modules/core/src/types.d.ts
Asynchronous data loading shouldn't be a concern of the Hubble library. This data prop was in conflict of that. Users should use deck.gl's asynchronous data loading features instead.
=> [chore] remove data param from DeckScene

modules/core/src/encoders/video/gif-encoder.js
Encoder settings coming in are read-only objects, so copy before assigning defaults to fix error.
=> [fix] Copy gif options before assignment.

docs/README.md, docs/api-reference/deck-adapter.md, docs/api-reference/scene/deck-scene.md, examples/camera/app.js, examples/kepler-integration/src/main.js, examples/terrain/app.js, examples/trips/app.js, examples/worldview/src/features/map/Map.js, examples/worldview/src/features/map/MapContainer.js, modules/core/src/adapters/deck-adapter.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/quick-animation.js
- async `new DeckAdapter({sceneBuilder})` removed, replaced by synchronous `scene` object parameter.
- `DeckAdapter.render({setReady})` is now optional since deck will only be referenced when recording.
- Removed complexity inside `DeckAdapter` implementation.
- Docs
=> [refactor] Make scene definition synchronous by supplying our own Timeline

docs/api-reference/deck-adapter.md, examples/worldview/src/app/App.js, examples/worldview/src/app/appSlice.js, examples/worldview/src/app/hooks.js, examples/worldview/src/app/index.js, examples/worldview/src/features/map/hooks.js, examples/worldview/src/features/map/index.js, examples/worldview/src/features/map/mapSlice.js, examples/worldview/src/scenes/newYork/index.js, examples/worldview/src/store.js, modules/core/src/adapters/deck-adapter.js
- [chore] remove DeckAdapter.getProps({setReady})
- [refactor] worldview remove "wait for ready" from lib
- Users can now use `deck.onLoad` in their apps without hubble overriding it.
=> [chore] remove unnecessary readiness checks

docs/README.md, docs/api-reference/deck-adapter.md, docs/api-reference/encoder/preview-encoder.md, docs/api-reference/scene/deck-scene.md, examples/camera/app.js, examples/quick-start/app.js, examples/terrain/app.js, examples/trips/app.js, examples/worldview/src/features/map/Map.js, examples/worldview/src/features/map/MapContainer.js, modules/core/src/adapters/deck-adapter.js, modules/core/src/scene/deck-scene.js, modules/core/src/types.d.ts, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/quick-animation.js
Remove `width` and `height` from DeckScene so that the class is only focused on managing animation state. Instead provide DeckGl with width and height prop directly to control its render resolution. Note mapbox still determines its dimension by filling whatever container it is put in, so deck and mapbox should be set to the same value if used together.
=> [chore] remove width and height from DeckScene

docs/api-reference/deck-adapter.md, docs/api-reference/scene/deck-scene.md, examples/camera/app.js, examples/camera/layers.js, examples/quick-start/app.js, examples/quick-start/quick-start-after.js, examples/terrain/app.js, examples/worldview/src/app/App.js, examples/worldview/src/features/kepler/hooks.js, examples/worldview/src/features/monitor/MonitorPanel.js, examples/worldview/src/features/renderer/hooks.js, examples/worldview/src/features/renderer/rendererMiddleware.js, examples/worldview/src/features/renderer/rendererSlice.js, examples/worldview/src/features/timeline/hooks.js, examples/worldview/src/features/timeline/timelineSlice.js, modules/core/src/adapters/deck-adapter.js, modules/core/src/keyframes/keyframes.js, modules/core/src/scene/deck-scene.js, modules/core/src/types.d.ts, modules/react/src/components/basic-controls.js, modules/react/src/components/quick-animation.js
**Changes**
- Instead of reserving `camera` key in keyframes object, give it a dedicated variable in DeckScene.
- For DeckScene construction, `initialKeyframes` split into `cameraKeyframes` and `layerKeyframes`.
- Added `scene.setCameraKeyframes` and `scene.getCameraFrame`
**Renamed**
- `scene.setKeyframes` to `scene.setLayerKeyframes`
- `scene.getFrame` to `scene.getLayerFrame`
- `scene.keyframes` to `scene.layerKeyframes`. Added `scene.cameraKeyframes`
- `getKeyframes` parameter renamed to `getLayerKeyframes` throughout DeckAdapter and examples.
=> [enhancement] split DeckScene keyframes up between layers and camera.

examples/worldview/src/features/map/MapContainer.js, examples/worldview/src/features/renderer/index.js, examples/worldview/src/features/renderer/rendererMiddleware.js, examples/worldview/src/features/renderer/rendererSlice.js
Since #119 and #112 simplified adapter construction, we can initialize the store adapter in the store right away instead of waiting for components to mount at runtime.
=> [enhancement] Add adapter to worldview store, initialized immediately

examples/worldview/src/features/map/Map.js, modules/react/src/components/export-video/export-video-panel-container.js
Match the kepler.gl animation controller initialization found in [bottom-widget](https://github.com/keplergl/kepler.gl/blob/14c35fc048a745faab0c6770cab7a4625ccedda3/src/components/bottom-widget.js#L148-L168)
- Only generate up to one filter keyframe, where `filter => filter.type === 'timeRange' && filter.enlarged` is true.
- Only generate up to one layer keyframe, where `showAnimationControl` is true.
```
const animatableLayer = layers.filter(
l => l.config.animation && l.config.animation.enabled && l.config.isVisible
);
const readyToAnimation =
Array.isArray(animationConfig.domain) && Number.isFinite(animationConfig.currentTime);
const showAnimationControl = animatableLayer.length && readyToAnimation;
```
=> [enhancement] Refine kepler.gl keyframe generation

examples/kepler-integration/src/components/export-video.js, modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-preview.js, modules/react/src/components/export-video/utils.js
Modifies the export window's viewState to match the main map bounds using `WebMercatorViewport.fitBounds`.
https://github.com/keplergl/kepler.gl/blob/master/src/utils/export-utils.js#L70-L91
https://github.com/keplergl/kepler.gl/blob/master/src/components/plot-container.js#L160-L172
=> [enhancement] Correct zoom scale and bounds in kepler video export

modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-settings.js, modules/react/src/components/export-video/export-video-panel.js, modules/react/src/components/export-video/modal-tab-edit.js, modules/react/src/components/export-video/modal-tab-export.js
- Consolidated props that are used for the export settings forms.
=> [chore] consolidate form setting props into an object

examples/kepler-integration/package.json, examples/worldview/package.json, modules/react/package.json, package.json
The pinned `hubble.gl` version in our examples were pulling `react-intl` from the published `@hubble.gl/react`. But `@hubble.gl/react` doesn't use `react-intl` anymore, so that should be removed. Once the new alpha is released, examples can include `hubble.gl` again, but this isn't necessary when using `yarn start-local`.
=> [bug] remove double install of react-intl

modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/modal-tab-edit.js
- save mapState when preview/render starts, and reset it when it ends
- Remove geographical move camera presets.
- halve resolution while previewing to improve performance
=> [enhancement] kepler, memo and return the viewState before/after rendering

modules/react/src/kepler-layers.js
The yellow on-hover highlights were visible in video exports if the mouse was in the map. This is not intended behavior.
=> [chore] remove hover highlight in video export modal

modules/react/src/components/export-video/export-video-panel-preview.js
For #157.
Test
- Open kepler-integration example, delete all layers, attempt to export video.
- Also should work when all layers are just "unseen"
=> fix(kepler) blank layer when no deck layers

examples/camera/package.json, examples/camera/webpack.config.js, examples/kepler-integration/package.json, examples/kepler-integration/webpack.config.js, examples/quick-start/package.json, examples/quick-start/webpack.config.js, examples/terrain/package.json, examples/terrain/webpack.config.js, examples/trips/package.json, examples/trips/webpack.config.js, examples/webpack.config.local.js, examples/worldview/package.json, examples/worldview/webpack.config.js
Supporting #160 and #159.
To use, run an example with `yarn start-local-luma` and install luma.gl for local development adjacent to the hubble repo.
```
code/
hubble.gl/
luma.gl/
```
=> add(examples) support for local luma.gl development

examples/worldview/src/features/kepler/hooks.js, examples/worldview/src/scenes/newYork/index.js, examples/worldview/src/scenes/sftrees/index.js
Adding a camera animation to the sftrees demo, and passing `cameraKeyframe` through the `useKepler` hook.
=> add(examples) sf trees animation

examples/worldview/src/features/map/DebugOverlay.js, examples/worldview/src/features/map/Map.js, examples/worldview/src/features/map/MapContainer.js, examples/worldview/src/features/monitor/MonitorPanel.js, examples/worldview/src/scenes/sftrees/index.js
Adding a `debug` prop to `Map` component when debugging resolutions. Related to #159
=> add(worldview) resolution debugger overlay and test resolutions

examples/worldview/src/features/map/Map.js, examples/worldview/src/features/map/MapContainer.js, examples/worldview/src/features/monitor/MonitorPanel.js, examples/worldview/src/features/monitor/Pillarbox.js, examples/worldview/src/utils.js
**Context**
The pillarbox effect is the black bars placed on the sides of video when video aspect ratio doesn't match container ratio.
We already had this effect implemented so no visual changes are expected in this PR, but now they are refactored into their own module.
**Basic Usage**
```jsx
// The export resolution.
const dimension = { width: 1280, height: 720 }
// Overlay is optional.
const overlay = <div>Centered Overlay!</div>
{/* The available space for a preview in the UI. */}
<div style={{width: 1000, height: 1000}}>
{/* Pillarbox grows to fill. */}
<Pillarbox dimension={dimension} overlay={overlay}>
{/* children are optional, a green box will render when undefined  */}
{/* previewSize is "dimension" scaled to fit the space available while maintaining aspect ratio.  */} …
```
=> add(worldview) Pillarbox component

modules/core/src/adapters/deck-adapter.js
**To Reproduce Bug**
1. Set deck.gl `_animate: true`. 
2. Resize the window or set a new dimension.
3. Notice all CSS rules passed to deck via `deckStyle` prop e.g. `transform: scale` do not update as expected, so the image goes off screen.
After review deck.gl code, `_animate` just forces `needsRedraw` to always return a reason, so `_drawLayers`  is always called (via `_customRender` in the react component). **Is there something in the deck.gl react component that prevents CSS style updates via `deckStyle` when `_animate: true`?**
**Before**
**After**
=> fix(worldview) only use _animate mode when rendering

examples/camera/app.js, examples/camera/layers.js, examples/quick-start/app.js, examples/terrain/app.js, examples/trips/app.js, modules/main/src/index.js, modules/react/src/hooks.js, modules/react/src/index.js
Use these hooks in react applications to reduce integration effort.
- Supports a deck.gl animation
- Optionally supports a base map for react-map-gl
```jsx
// minimal integration
import { useDeckAnimation, useHubbleGl} from '@hubble.gl/react';
const deckRef = useRef(null);
const staticMapRef = useRef(null); // optional base map
const deckAnimation = useDeckAnimation({
getLayers: ...
layerKeyframes: ...
cameraKeyframe: ...
});
const {deckProps, staticMapProps, adapter, cameraFrame, setCameraFrame} = useHubbleGl({
deckRef,
staticMapRef,
deckAnimation,
initialViewState
});
<DeckGL
ref={deckRef}
viewState={cameraFrame}
{/* add props before spreading hubble props */}
{...deckProps}
>
{/* optional base map */
{staticMapProps.gl && (
<StaticMap
ref={staticMapRef}
{/* add props before spreading …
```
=> add(react) useHubbleGl and useDeckAnimation hook

modules/react/src/components/export-video/export-video-panel-preview.js
Prevent crash when static map isn't used
=> fix(video-preview) don't call getMap when disableStaticMap is set

modules/react/src/components/export-video/modal-tab-animation.js
Atm, it's possible to set animation time to 0, click on the preview button.
This causes an internal assertion crash which leaves the preview modal in a partially broken state.
=> fix(ui) clamp min animation time

modules/react/src/components/export-video/modal-tab-settings.js
`~` can be misread in some fonts and situations as a negative number, so suggesting "Approx." instead.
=> Estimate file size with "Approx." rather than ~

modules/core/src/adapters/deck-adapter.js, modules/core/src/capture/video-capture.js, modules/react/src/components/export-video/export-video-panel-container.js
Adds an `abort` option to the `stop` functions to override the default behavior of processing partial renders. When abort is true, the captured frames are fully discarded as if the render never started.
=> enhance(capture) add support to skip processing a render, full abort.

modules/react/src/components/export-video/export-video-panel-preview.js
- don't call onAfterRender after export-video-panel unmount.
=> fix(video-export-panel): don't call onAfterRender after unmount

modules/react/src/components/export-video/export-video-panel-container.js, modules/react/src/components/export-video/export-video-panel-preview.js
- move this.onStop({abort: true}) to componentWillUnmount
- release mapbox map in componentWillUnmount
=> fix(video-export-panel-container): abort video on unmount, properly unsubscribe mapbox

examples/get-started/pure-js/app.js, examples/get-started/pure-js/package.json, examples/get-started/standalone/index.html, examples/get-started/standalone/package.json, examples/kepler/index.html, examples/kepler/package.json, examples/kepler/src/main.js, examples/kepler/webpack.config.js, examples/website/basic-basemap/app.js, examples/website/basic-basemap/package.json, examples/website/camera/app.js, examples/website/camera/package.json, examples/website/quick-start/app.js, examples/website/quick-start/package.json, examples/website/terrain/app.js, examples/website/terrain/package.json, examples/website/trips/app.js, examples/website/trips/package.json, examples/worldview/package.json
- removing deck.gl 8.2.0 pin
- pinning mapbox v1 in examples for open license
- example builds are isolated and can be copied to their own environment
=> fix(examples) isolate builds and unpin deck.gl version

examples/website/basic-basemap/README.md, examples/website/basic-basemap/app.jsx, examples/website/basic-basemap/package.json, examples/website/basic-basemap/set-ref.ts, examples/website/basic-basemap/vite.config.js, modules/react/src/hooks.ts
- removes deprecated `MapboxLayer`
- switches `basic-basemap` example to maplibre
- demonstrates using `@deck.gl/mapbox`'s `MapboxOverlay` instead of `@deck.gl/react`'s `DeckGL` for rendering deck in a basemap context
- update readme example
=> [react] MapboxOverlay-ready hooks and `basic-basemap` example

modules/main/src/index.ts, test/imports-spec.ts, test/modules.ts, test/node.ts
- Adding a top-level import test to ensure that all of the hubble.gl modules are correctly exported.
- Added missing exports to the main package.
- Node tests fail to import deck.gl's typed modules, so they've been disabled. Hopefully this issue is resolved with the v9 upgrade.
=> chore(main) add top-level import test

modules/core/package.json, modules/core/src/utils/log.ts, modules/react/package.json, modules/react/src/components/render-player.tsx, package.json, test/node.ts, yarn.lock
- Upgrade loaders.gl@4.3 and probe.gl@4.1 to resolve issues with new build tools in #300
- Removes usages to main `probe.gl` package, which is no longer updated. Using this package now breaks TypeScript builds since the types have changed significantly.
- ![Screenshot 2025-02-04 at 5 08 07 PM](https://github.com/user-attachments/assets/549d1b30-9b39-44af-9782-130e0ab2ce4a)
- Add explicit puppeteer dependency rather than rely on a global install
- Disables node tests due to continuing issues with `document.createElement` in `loaders.gl/video`: https://github.com/visgl/loaders.gl/issues/2164
- ![Screenshot 2025-02-04 at 5 16 26 PM](https://github.com/user-attachments/assets/715999d7-0a28-4722-91d3-dd8a0455adef)
=> Upgrade loaders.gl@4.3 and probe.gl@4.1

package.json, yarn.lock
`node_modules` is removed during website action, meaning `pre-push` doesn't exist and git crashes during push.
Here's an example of the error: https://github.com/visgl/hubble.gl/actions/runs/13193591312
We don't need pre-push since pre-commit does the same thing, and we have CI. This PR removes it.
=> fix(website) remove pre-push to fix website action

.github/workflows/release.yml
Released [failed](https://github.com/visgl/hubble.gl/actions/runs/13979754983/job/39142195898) since [distribution tests](https://github.com/visgl/dev-tools/blob/ef50bfbaed323174b37148a4716b7894069d5404/modules/dev-tools/scripts/test.sh#L56-L58C28) both node and browser.
=> Only run browser tests on release
